version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: lovepotion_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: LjmX4r6w3FM21BZlOyCUmXUZuDiIaZbN
